import Link from "next/link";
import { cars, formatPrice } from "@/lib/cars";

const leads=[
 {name:"Rahul Sharma",car:"2022 Hyundai Creta SX",source:"WhatsApp",status:"New"},
 {name:"Aman Verma",car:"2021 Mahindra Thar LX",source:"Website",status:"Qualified"},
 {name:"Priya Singh",car:"2023 Kia Seltos GTX",source:"Google",status:"Appointment"},
 {name:"Vikram Gill",car:"2020 Toyota Fortuner 4x2",source:"Instagram",status:"Follow-up"},
];
export default function Dashboard(){return <><header className="topbar"><div className="container nav"><div className="brand">DEALERSHIP DASHBOARD</div><Link className="navlinks" href="/inventory">View inventory</Link></div></header><main className="section"><div className="container"><h1>Sales & Lead Dashboard</h1><p className="muted">MVP dashboard using mock lead data. Replace with Supabase/CRM data later.</p><div className="stats"><div className="stat"><span className="muted">Inventory</span><strong>{cars.length}</strong></div><div className="stat"><span className="muted">Available</span><strong>{cars.filter(c=>c.status==="Available").length}</strong></div><div className="stat"><span className="muted">New leads</span><strong>4</strong></div><div className="stat"><span className="muted">Qualified rate</span><strong>25%</strong></div></div><section className="section" style={{paddingBottom:0}}><h2>Lead pipeline</h2><div style={{overflowX:"auto",background:"#fff",border:"1px solid #e5e7eb",borderRadius:14}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={{textAlign:"left",padding:16}}>Lead</th><th style={{textAlign:"left",padding:16}}>Vehicle</th><th style={{textAlign:"left",padding:16}}>Source</th><th style={{textAlign:"left",padding:16}}>Status</th></tr></thead><tbody>{leads.map((l,i)=><tr key={i} style={{borderTop:"1px solid #e5e7eb"}}><td style={{padding:16}}>{l.name}</td><td style={{padding:16}}>{l.car}</td><td style={{padding:16}}>{l.source}</td><td style={{padding:16}}><span className="pill">{l.status}</span></td></tr>)}</tbody></table></div><h2 style={{marginTop:34}}>Inventory value</h2><p className="muted">Available stock value: <strong>{formatPrice(cars.filter(c=>c.status==="Available").reduce((a,c)=>a+c.price,0))}</strong></p></section></div></main></>}
