import Link from 'next/link';
import { ArrowUpRight, CarFront, MessageSquare, CalendarCheck, TrendingUp } from 'lucide-react';
import { leads } from '@/lib/cars';

const cls=(s:string)=>s.toLowerCase().replaceAll(' ','-');
export default function Dashboard(){return <>
<div className="topbar"><div><p className="eyebrow">DEALERSHIP OS</p><h1 className="page-title">Good morning, VandLabs</h1><p className="muted">Here’s what is happening across your dealership.</p></div><Link className="btn btn-brand" href="/dashboard/inventory">+ Add vehicle</Link></div>
<div className="dashboard-grid">
{[['Active inventory','8','+2 this week',CarFront],['New leads','42','+18% vs last month',MessageSquare],['Appointments','12','4 today',CalendarCheck],['Qualified rate','64%','+6.4% this month',TrendingUp]].map(([l,v,c,I])=><div className="stat" key={l as string}><div className="stat-label">{l as string}</div><div className="stat-value">{v as string}</div><div className="stat-change green">{c as string}</div></div>)}
</div>
<div className="two-col"><section className="panel"><div className="panel-head"><div><div className="panel-title">Recent leads</div><div className="muted" style={{fontSize:12}}>Latest enquiries from all channels</div></div><Link href="/dashboard/leads" className="btn btn-light">View all <ArrowUpRight size={14}/></Link></div><div className="table-wrap"><table className="table"><thead><tr><th>Lead</th><th>Vehicle</th><th>Source</th><th>Status</th><th>Received</th></tr></thead><tbody>{leads.slice(0,5).map(l=><tr key={l.id}><td><strong>{l.name}</strong><br/><span className="muted">{l.phone}</span></td><td>{l.vehicle}</td><td>{l.source}</td><td><span className={'status '+cls(l.status)}>{l.status}</span></td><td className="muted">{l.time}</td></tr>)}</tbody></table></div></section>
<section className="panel"><div className="panel-head"><div><div className="panel-title">Lead funnel</div><div className="muted" style={{fontSize:12}}>This month</div></div></div><div className="metric-row"><span>Enquiries</span><strong>42</strong></div><div className="metric-row"><span>Contacted</span><strong>35</strong></div><div className="metric-row"><span>Qualified</span><strong>27</strong></div><div className="metric-row"><span>Appointments</span><strong>12</strong></div><div className="metric-row"><span>Test drives</span><strong>8</strong></div><div className="metric-row"><span>Sales attributed</span><strong className="green">4</strong></div></section></div>
<div className="two-col"><section className="panel"><div className="panel-head"><div className="panel-title">Enquiries by channel</div><span className="muted">Last 7 days</span></div><div className="chart">{[35,48,42,65,52,78,90].map((x,i)=><div className="bar" style={{height:x+'%'}} key={i}><span>{['M','T','W','T','F','S','S'][i]}</span></div>)}</div></section><section className="panel"><div className="panel-head"><div className="panel-title">Inventory attention</div><Link href="/dashboard/inventory" className="muted">Manage</Link></div>{[['Creta SX','18 enquiries'],['Fortuner 4x4','11 enquiries'],['Seltos GTX+','8 enquiries'],['Kushaq Style','5 enquiries']].map(x=><div className="metric-row" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</section></div>
</>}
